use crate::robot::types::Pose;

/// Three semantic views of the same physical state sample.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct StateView<T> {
    /// Sensor feedback / estimator output.
    pub meas: T,
    /// Last command accepted by the low-level controller.
    pub cmd: T,
    /// Reference generated by the planner / controller.
    pub des: T,
}

impl<T: Default> Default for StateView<T> {
    fn default() -> Self {
        Self { meas: T::default(), cmd: T::default(), des: T::default() }
    }
}

impl<T: Default> StateView<T> {
    pub fn from_meas(meas: T) -> Self {
        Self { meas, ..Default::default() }
    }
}

/// One sample of joint-space telemetry.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct JointSample<const N: usize> {
    /// Joint position vector, normally in radians for revolute joints.
    pub q: Option<[f64; N]>,
    /// Joint velocity vector.
    pub dq: Option<[f64; N]>,
    /// Joint acceleration vector.
    pub ddq: Option<[f64; N]>,
    /// Joint torque / generalized effort vector.
    pub tau: Option<[f64; N]>,
    /// Time derivative of joint torque / effort.
    pub dtau: Option<[f64; N]>,
}

pub type JointState<const N: usize> = StateView<JointSample<N>>;

/// One sample of spatial pose / twist / wrench telemetry.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SpatialSample {
    /// Pose of the spatial frame in the relevant parent frame.
    pub pose: Option<Pose>,
    /// Spatial velocity `[vx, vy, vz, wx, wy, wz]`.
    pub vel: Option<[f64; 6]>,
    /// Spatial acceleration `[ax, ay, az, alpha_x, alpha_y, alpha_z]`.
    pub acc: Option<[f64; 6]>,
    /// Spatial force / torque `[fx, fy, fz, tx, ty, tz]`.
    pub wrench: Option<[f64; 6]>,
}

impl Default for SpatialSample {
    fn default() -> Self {
        Self {
            pose: Some(Pose::default()),
            vel: Some([0.; 6]),
            acc: Some([0.; 6]),
            wrench: Some([0.; 6]),
        }
    }
}

pub type BaseState = StateView<SpatialSample>;
pub type EndEffectorState = StateView<SpatialSample>;

/// One sample of contact telemetry.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ContactSample {
    /// Whether the contact is currently active.
    pub on: bool,
    /// Contact force vector.
    pub f: Option<[f64; 3]>,
    /// Contact point position.
    pub p: Option<[f64; 3]>,
    /// Contact normal direction.
    pub n: Option<[f64; 3]>,
}

impl Default for ContactSample {
    fn default() -> Self {
        Self {
            on: false,
            f: Some([0.; 3]),
            p: Some([0.; 3]),
            n: Some([0.; 3]),
        }
    }
}

pub type ContactState = StateView<ContactSample>;

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct MobileBaseState {
    /// Base pose / twist / wrench state.
    pub base: BaseState,
}

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct QuadrupedState<const N: usize> {
    /// Whole-body joint state for the quadruped.
    pub joint: JointState<N>,
    /// Floating or mobile base state.
    pub base: BaseState,
    /// Per-foot pose / twist / wrench state.
    pub feet: [EndEffectorState; 4],
    /// Per-foot contact state.
    pub contacts: [ContactState; 4],
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct HumanoidState<const N: usize> {
    /// Whole-body joint state for the humanoid.
    pub joint: JointState<N>,
    /// Floating or mobile base state.
    pub base: BaseState,
    /// Per-hand pose / twist / wrench state.
    pub hands: [EndEffectorState; 2],
    /// Per-foot pose / twist / wrench state.
    pub feet: [EndEffectorState; 2],
    /// Contact states for feet, hands or other contact surfaces.
    pub contacts: Vec<ContactState>,
}
